# -*- coding: utf-8 -*-
"""MangoScan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uNAJrQdVvYW5raGqc8ogL8LmsqgzRjr
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive/MangoScanDataset/archive1/Dataset"))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Generator untuk training (resize, normalisasi, augmentasi)
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2]
)

# Generator untuk testing (hanya resize + normalisasi)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    "/content/drive/MyDrive/MangoScanDataset/archive1/Dataset/train",  # sesuaikan huruf besar/kecil
    target_size=(224,224),
    batch_size=16,
    class_mode="categorical"
)

test_generator = test_datagen.flow_from_directory(
    "/content/drive/MyDrive/MangoScanDataset/archive1/Dataset/test",   # sesuaikan huruf besar/kecil
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(5, activation='softmax')  # 5 kelas
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(
    train_generator,
    epochs=5,
    validation_data=test_generator
)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

Y_pred = model.predict(test_generator)
y_pred = np.argmax(Y_pred, axis=1)

print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred))

print('Classification Report')
target_names = list(test_generator.class_indices.keys())
print(classification_report(test_generator.classes, y_pred, target_names=target_names))

model.save("/content/drive/MyDrive/MangoScanModel.h5")

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# fungsi prediksi
def predict_image(img_path):
    img = image.load_img(img_path, target_size=(224,224))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    classes = list(train_generator.class_indices.keys())
    plt.imshow(image.load_img(img_path))
    plt.axis("off")
    plt.show()
    print("Prediksi:", classes[np.argmax(prediction)])


predict_image("/content/drive/MyDrive/MangoScanDataset/archive1/Dataset/test/Ripe/matang.jpg")
predict_image("/content/drive/MyDrive/MangoScanDataset/archive1/Dataset/test/Partially ripe/setengahmatang.jpg")
predict_image("/content/drive/MyDrive/MangoScanDataset/archive1/Dataset/test/Unripe/mentah.jpg")

!pip install gradio

import gradio as gr
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

# Load model yang sudah kamu simpan
model = load_model("/content/drive/MyDrive/MangoScanModel.h5")
classes = ["mentah", "setengah_matang", "matang", "masih_mentah", "busuk"]

def predict_mango(img):
    img = image.img_to_array(img) / 255.0
    img = np.expand_dims(img, axis=0)
    prediction = model.predict(img)
    return {classes[i]: float(prediction[0][i]) for i in range(len(classes))}

# Buat interface Gradio
interface = gr.Interface(
    fn=predict_mango,
    inputs=gr.Image(type="pil", label="Upload Foto Mangga"),
    outputs=gr.Label(num_top_classes=5),
    title="🍋 MangoScan",
    description="Upload foto mangga untuk prediksi tingkat kematangan."
)

interface.launch(share=True)  # share=True biar dapat link publik

from google.colab import files
uploaded = files.upload()

from tensorflow.keras.preprocessing import image
import numpy as np

img = image.load_img("/content/IMG20200717083707.jpg", target_size=(224,224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)
classes = list(train_generator.class_indices.keys())
print("Prediksi:", classes[np.argmax(prediction)])

import gradio as gr
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

# Load model yang sudah kamu simpan
model = load_model("/content/drive/MyDrive/MangoScanModel.h5")
classes = ["mentah", "setengah_matang", "matang", "masih_mentah", "busuk"]

def predict_mango(img):
    img = img.convert("RGB")
    img = image.img_to_array(img) / 255.0
    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img)[0]
    return {classes[i]: float(prediction[i]) for i in range(len(classes))}


# Buat interface Gradio
interface = gr.Interface(
    fn=predict_mango,
    inputs=gr.Image(type="pil"),
    outputs="text"
)

interface.launch(share=True)  # share=True biar dapat link publik

import gradio as gr
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

# Load model
model = load_model("/content/drive/MyDrive/MangoScanModel.h5")
classes = ["Mentah", "Setengah Matang", "Matang", "Terlalu Matang", "Busuk"]

def predict_mango(img):
    try:
        # pastikan gambar RGB dan resize ke ukuran training
        img = img.convert("RGB").resize((224,224))
        img = image.img_to_array(img) / 255.0
        img = np.expand_dims(img, axis=0)

        prediction = model.predict(img)[0]
        pred_class = classes[np.argmax(prediction)]
        confidence = float(np.max(prediction))

        return f"Prediksi: {pred_class} (confidence: {confidence:.2f})"
    except Exception as e:
        return f"Error: {str(e)}"

# Interface Gradio
interface = gr.Interface(
    fn=predict_mango,
    inputs=gr.Image(type="pil", label="Upload Foto Mangga"),
    #outputs="text",   # pakai text biar aman
    outputs=gr.Label(num_top_classes=5),
    title="🍋 MangoScan",
    description="Upload foto mangga untuk prediksi tingkat kematangan."
)

interface.launch(share=True)